import Header from './components/Header/Header'
import TopBar from './components/TopBar/TopBar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TopBar/>
        <Header/>
        <main>{children}</main>
        </body>
    </html>
  )
}
